@BaseUrl=http://localhost:8080

###
GET {{BaseUrl}}/shorten/

###
GET {{BaseUrl}}/shorten/7819e

###
GET {{BaseUrl}}/shorten/7819e/stats


###
POST {{BaseUrl}}/shorten/
Accept: application/json
Content-Type: application/json

{
	"url": "http://google13.com"
}

###
PUT  {{BaseUrl}}/shorten/00943

{
	"url": "http://google1220.com"
}

###
DELETE  {{BaseUrl}}/shorten/2d003