@BaseUrl=http://localhost:8090

###
GET {{BaseUrl}}/shorten/

###
GET {{BaseUrl}}/shorten/2d003

###
GET {{BaseUrl}}/shorten/2d003/stats


###
POST {{BaseUrl}}/shorten/
Accept: application/json
Content-Type: application/json

{
	"url": "http://google12.com"
}

###
PUT  {{BaseUrl}}/shorten/00943

{
	"url": "http://google1220.com"
}

###
DELETE  {{BaseUrl}}/shorten/2d003