profile: lambda
spring:
  application:
    name: url-shortner
  datasource:
    url: "jdbc-secretsmanager:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: "${RDS_SECRET_NAME}"
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: off
    properties:
      hibernate:
        format_sql: true
    database: postgresql
server:
  port: ${PORT}
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG